{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "backend-template.fullname" . }}-external-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend-template.labels" . | nindent 4 }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: gitlab-clustersecretstore
    kind: ClusterSecretStore
  target:
    name: {{ include "backend-template.fullname" . }}-secret
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key | default .secretKey }}
    {{- end }}
{{- end }}