apiVersion: v1
kind: Service
metadata:
  name: {{ include "<CHARTNAME>.fullname" . }}
  labels:
    {{- include "<CHARTNAME>.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: api
      protocol: TCP
      name: api
    {{- if .Values.service.mcp.enabled }}
    - port: {{ .Values.service.mcp.port }}
      targetPort: mcp
      protocol: TCP
      name: mcp
    {{- end }}
  selector:
    {{- include "<CHARTNAME>.selectorLabels" . | nindent 4 }}
