global:
  domain: v2.argocd.haulrest.me

configs:
  params:
    server.insecure: true
  cm:
    url: https://v2.argocd.haulrest.me
    dex.config: |
      connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $oauth-secret:clientId
          clientSecret: $oauth-secret:clientSecret
          loadAllGroups: true
          orgs:
            - name: BeaverHouse
  rbac:
    policy.csv: |
      g, BeaverHouse:Owner, role:admin

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    tls: true
