# Cloud cluster configuration

services:
  file-manager:
    enabled: true
  llm-client:
    enabled: true
  search-manager:
    enabled: true
  smart-manager:
    enabled: true

# Add weighted routing annotations for all services
file-manager:
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/set-identifier: "cloud-cluster"
      external-dns.alpha.kubernetes.io/aws-weight: "50"

llm-client:
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/set-identifier: "cloud-cluster"
      external-dns.alpha.kubernetes.io/aws-weight: "50"

search-manager:
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/set-identifier: "cloud-cluster"
      external-dns.alpha.kubernetes.io/aws-weight: "50"

smart-manager:
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/set-identifier: "cloud-cluster"
      external-dns.alpha.kubernetes.io/aws-weight: "50"
