replicaCount: 1

image:
  repository: ghcr.io/beaverhouse/aecheck-backend
  pullPolicy: IfNotPresent
  tag: "sha-65ccc1a"

imagePullSecrets:
  - name: ghcr-secret

nameOverride: "aecheck-backend"
fullnameOverride: "aecheck-backend"

serviceAccount:
  create: false

service:
  type: ClusterIP
  api:
    port: 5050
  mcp:
    enabled: false
    port: 3000

resources:
  limits:
    cpu: 50m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 128Mi

autoscaling:
  enabled: false

# Health check configuration
livenessProbe:
  httpGet:
    path: /aecheck/dungeon
    port: api
  periodSeconds: 90

readinessProbe:
  httpGet:
    path: /aecheck/dungeon
    port: api
  periodSeconds: 90

# ExternalSecret configuration
externalSecret:
  enabled: true
  data:
    - secretKey: "POSTGRES_HOST"
      remoteRef:
        key: "SUPABASE_POSTGRES_HOST"
    - secretKey: "POSTGRES_PORT"
      remoteRef:
        key: "SUPABASE_POSTGRES_PORT"
    - secretKey: "POSTGRES_USER"
      remoteRef:
        key: "SUPABASE_POSTGRES_USER"
    - secretKey: "POSTGRES_PASSWORD"
      remoteRef:
        key: "SUPABASE_POSTGRES_PASSWORD"
    - secretKey: "POSTGRES_DBNAME"
      remoteRef:
        key: "SUPABASE_POSTGRES_DBNAME"

# Custom deployment configuration for environment variables
envFrom:
  - secretRef:
      name: aecheck-backend-secret
