apiVersion: v2
name: app-tiny-clover-umbrella
description: Umbrella chart for tiny-clover applications
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: app-tiny-clover
    alias: file-manager
    version: "0.1.0"
    repository: "file://../app-tiny-clover"
    condition: services.file-manager.enabled
  - name: app-tiny-clover
    alias: llm-client
    version: "0.1.0"
    repository: "file://../app-tiny-clover"
    condition: services.llm-client.enabled
  - name: app-tiny-clover
    alias: search-manager
    version: "0.1.0"
    repository: "file://../app-tiny-clover"
    condition: services.search-manager.enabled
  - name: app-tiny-clover
    alias: smart-manager
    version: "0.1.0"
    repository: "file://../app-tiny-clover"
    condition: services.smart-manager.enabled