apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oss-argocd-config-application
  namespace: argo-project
spec:
  project: default
  source:
    repoURL: https://github.com/BeaverHouse/hybrid-cicd.git
    targetRevision: main
    path: charts/oss-argocd/resources
  destination:
    name: in-cluster
    namespace: argo-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
