apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gitlab-clustersecretstore
spec:
  provider:
    # provider type: gitlab
    gitlab:
      auth:
        SecretRef:
          accessToken:
            namespace: external-secrets
            name: gitlab-eso-secret
            key: token
      projectID: "70159864" # Your GitLab project ID where the secrets are stored
      inheritFromGroups: true
