apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: haulrest@gmail.com
    privateKeySecretRef:
      name: letsencrypt-private-key
    solvers:
      - dns01:
          cnameStrategy: Follow
          route53:
            region: ap-northeast-2
            accessKeyIDSecretRef:
              name: route53-secret
              key: AWS_ACCESS_KEY_ID_DNS
            secretAccessKeySecretRef:
              name: route53-secret
              key: AWS_SECRET_ACCESS_KEY_DNS
