apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-legacy-backends
  namespace: argo-project
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: aecheck-backend
            project: cloud
            valuesFile: aecheck.yaml
            cluster: cloud-k8s
          - name: file-server
            project: cloud
            valuesFile: file.yaml
            cluster: cloud-k8s
  template:
    metadata:
      name: "{{ .name }}-legacy"
      labels:
        app.kubernetes.io/name: "{{ .name }}"
        custom-image: "true"
        app.kubernetes.io/part-of: legacy-backends
    spec:
      project: "{{ .project }}"
      source:
        repoURL: https://github.com/BeaverHouse/hybrid-cicd.git
        targetRevision: main
        path: charts/app-legacy-backends
        helm:
          valueFiles:
            - values/{{ .valuesFile }}
      destination:
        name: "{{ .cluster }}"
        namespace: legacy-backends
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
