apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-legacy-backends
  namespace: argo-project
spec:
  generators:
    - list:
        elements:
          - name: aecheck-backend
            valuesFile: aecheck.yaml
            cluster: cloud-k8s
          - name: file-server
            valuesFile: file.yaml
            cluster: cloud-k8s
  template:
    metadata:
      name: "{{ .name }}"
      labels:
        app.kubernetes.io/name: "{{ .name }}"
        custom-image: "true"
        app.kubernetes.io/part-of: legacy-backends
    spec:
      project: home-server
      source:
        repoURL: https://github.com/AustinLee/hybrid-k8s-docker-helm
        targetRevision: HEAD
        path: charts/app-legacy-backends
        helm:
          valueFiles:
            - values/{{ .valuesFile }}
      destination:
        name: "{{ .cluster }}"
        namespace: legacy-backends
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        # Not creating namespace, because it is already created by the cluster.
