apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-clustersecrets-applicationset
  namespace: argo-project
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: cloud
            project: cloud
            cluster: cloud-k8s
  template:
    metadata:
      name: "{{ .name }}-app-clustersecrets"
    spec:
      project: "{{ .project }}"
      source:
        repoURL: https://github.com/BeaverHouse/hybrid-cicd.git
        targetRevision: main
        path: charts/app-clustersecrets/resources
      destination:
        name: "{{ .cluster }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
