apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-clustersecrets-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: cloud-k8s
            project: cloud
  template:
    metadata:
      name: "{{cluster}}-app-clustersecrets"
    spec:
      project: "{{project}}"
      source:
        repoURL: https://github.com/BeaverHouse/hybrid-k8s-docker-helm.git
        targetRevision: main
        path: charts/app-clustersecrets
      destination:
        name: "{{cluster}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
