apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: oss-ingress-nginx-applicationset
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: cloud
            project: cloud
            cluster: cloud-k8s
  template:
    metadata:
      name: "oss-ingress-nginx-{{ .name }}"
    spec:
      project: "{{ .project }}"
      sources:
        - repoURL: https://kubernetes.github.io/ingress-nginx
          targetRevision: 4.13.0
          chart: ingress-nginx
          helm:
            releaseName: "ingress-nginx"
            valueFiles:
              - $customRepo/charts/oss-ingress-nginx/values.yaml
        - repoURL: https://github.com/lhu/hybrid-k8s-docker-helm
          targetRevision: main
          ref: customRepo
      destination:
        name: "{{ .cluster }}"
        namespace: ingress-nginx
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
