replicaCount: 1

image:
  repository: ghcr.io/beaverhouse/tinyclover-smart-manager
  pullPolicy: IfNotPresent
  tag: "ba41dec3"

imagePullSecrets:
  - name: ghcr-secret

nameOverride: "smart-manager"
fullnameOverride: "smart-manager"

serviceAccount:
  create: false

service:
  type: ClusterIP
  api:
    port: 8083
  mcp:
    enabled: true
    port: 8103

resources:
  limits:
    cpu: 50m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 128Mi

autoscaling:
  enabled: false

# Health check configuration
livenessProbe:
  httpGet:
    path: /smart-manager/v1/health
    port: api
  periodSeconds: 120

readinessProbe:
  httpGet:
    path: /smart-manager/v1/health
    port: api
  periodSeconds: 120

# ExternalSecret configuration
externalSecret:
  enabled: true
  data:
    - secretKey: "POSTGRES_HOST"
      remoteRef:
        key: "SUPABASE_POSTGRES_HOST"
    - secretKey: "POSTGRES_USER"
      remoteRef:
        key: "SUPABASE_POSTGRES_USER"
    - secretKey: "POSTGRES_PASSWORD"
      remoteRef:
        key: "SUPABASE_POSTGRES_PASSWORD"
    - secretKey: "SUPABASE_JWT_KEYFUNC_URL"
      remoteRef:
        key: "SUPABASE_JWT_KEYFUNC_URL"

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    # Not add externalDNS annotation, because it's duplicate with file-manager
  hosts:
    - host: api.tinyclover.com
      paths:
        - path: /smart-manager/v1
          pathType: Prefix
  tls:
    - secretName: smart-manager-tls
      hosts:
        - api.tinyclover.com

# Custom deployment configuration for environment variables
envFrom:
  - secretRef:
      name: smart-manager-secret

extraEnv:
  - name: GO_ENV
    value: "production"
  - name: MCP_BASE_URL
    value: "http://smart-manager.tiny-clover.svc.cluster.local:8103/smart-manager/v1"
  - name: MCP_TRANSPORT
    value: "http"
