controller:
  kind: DaemonSet
  service:
    externalTrafficPolicy: Cluster
    enableHttp: true
    ports:
      http: 80
      https: 443
    targetPorts:
      http: http
      https: https
    annotations:
      service.beta.kubernetes.io/vultr-load-balancer-protocol: "https"
